# resolver: lts-20.1
resolver: nightly-2024-01-26

packages:
  - .
extra-deps:
  - store-0.7.18@sha256:af32079e0d31413b97a1759f8ad8555507857cd4ac4015e195fb5b0a27a3ce9f,8159
  - store-core-0.4.4.7@sha256:a2ea427ff0dde30252474dcb0641cb6928cb8a93cd5ee27d4c22adba8e729683,1489
  - rest-rewrite-0.4.3
  - smtlib-backends-0.3@rev:2
  - smtlib-backends-process-0.3@rev:2
  - git: https://github.com/ucsd-progsys/liquidhaskell
    commit: 4b20537529b2143cab0214564422c94fb93df9d9
    subdirs:
      - .
      - liquidhaskell-boot
      - liquid-prelude
      - liquid-vector
  - git: https://github.com/ucsd-progsys/liquid-fixpoint
    commit: 5b39f1a3c49190f9e438f9cdefd7d2635c5bf7f2

nix:
  packages: [cacert, git, hostname, z3]
