resolver: lts-19.33
packages:
  - .
extra-deps:
  - rest-rewrite-0.4.0
  - git: https://github.com/ucsd-progsys/liquidhaskell
    commit: 797f27d191b82bb3aa55e686ebc15481ebc6bee4
    subdirs:
      - .
      - liquid-base
      - liquid-prelude
      - liquid-ghc-prim
      - liquid-containers
  - git: https://github.com/ucsd-progsys/liquid-fixpoint
    commit: a45f8fe9f6ac2533228f9149926bf884a3525945

nix:
  packages: [cacert, git, hostname, z3]
